"""crear_tablas

Revision ID: 83f585f50595
Revises: 
Create Date: 2026-05-05 22:03:03.514249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '83f585f50595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_final', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_historia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_alta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reingreso_48', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especialidad_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingreso_urgencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fallecimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apache', sa.Float(), nullable=True),
    sa.Column('vmi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dias_vmi', sa.Float(), nullable=True),
    sa.Column('barotrauma', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grados_inclinacion', sa.Float(), nullable=True),
    sa.Column('episodios_nav', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registro_intubaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extubacion_programada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extubacion_maniobras', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sepsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shock_septico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pam_ingreso', sa.Float(), nullable=True),
    sa.Column('pam_6h', sa.Float(), nullable=True),
    sa.Column('pam_24h', sa.Float(), nullable=True),
    sa.Column('diuresis_ingreso', sa.Float(), nullable=True),
    sa.Column('diuresis_6h', sa.Float(), nullable=True),
    sa.Column('diuresis_24h', sa.Float(), nullable=True),
    sa.Column('lactato_ingreso', sa.Float(), nullable=True),
    sa.Column('lactato_6h', sa.Float(), nullable=True),
    sa.Column('lactato_24h', sa.Float(), nullable=True),
    sa.Column('tratamiento_adecuado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cobertura_empirica_completa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resistencia_antibioticos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_episodios_bacteriemia', sa.Float(), nullable=True),
    sa.Column('numero_total_dias_cvc', sa.Float(), nullable=True),
    sa.Column('rass', sa.Float(), nullable=True),
    sa.Column('bis', sa.Float(), nullable=True),
    sa.Column('rass_objetivo', sa.Float(), nullable=True),
    sa.Column('bis_objetivo', sa.Float(), nullable=True),
    sa.Column('ventana_sedacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_inicio_ne', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('omeprazol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tratamiento_corticoides', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('antecedentes_hemorragia_gi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coagulopatia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insuficiencia_renal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insuficiencia_hepatica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profilaxis_tvp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tvp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('glucemia', sa.Float(), nullable=True),
    sa.Column('tratamiento_insulina', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traslado_intrahospitalario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listado_verificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('eventos_adversos_traslado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actos_transfusionales', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sangrado_activo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cantidad_transfusion_dia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuariodb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuariodb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuariodb_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuariodb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuariodb_email'))

    op.drop_table('usuariodb')
    op.drop_table('registro')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
